CREATE DATABASE Airport
USE Airport
GO
--01.

CREATE TABLE Passengers
(
	Id INT PRIMARY KEY IDENTITY,
	FullName NVARCHAR(100) NOT NULL UNIQUE,
	Email NVARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE Pilots
(
	Id INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(30) NOT NULL UNIQUE,
	LastName NVARCHAR(30) NOT NULL UNIQUE,
	Age TINYINT  NOT NULL CHECK(Age BETWEEN 21 AND 62),
	Rating FLOAT CHECK(Rating BETWEEN 0.0 AND 10.0),
)


CREATE TABLE AircraftTypes
(
	Id INT PRIMARY KEY IDENTITY,
	TypeName NVARCHAR(30) NOT NULL UNIQUE
)

CREATE TABLE Aircraft
(
	Id INT PRIMARY KEY IDENTITY,
	Manufacturer NVARCHAR(25) NOT NULL,
	Model NVARCHAR(30) NOT NULL,
	Year INT NOT NULL,
	FlightHours INT ,
	Condition CHAR(1) NOT NULL,
	TypeId INT NOT NULL,
	FOREIGN KEY (TypeId) REFERENCES AircraftTypes(Id)
)

CREATE TABLE PilotsAircraft
(
	AircraftId INT NOT NULL,
	PilotId INT NOT NULL,
	PRIMARY KEY(AircraftId, PilotId),
	FOREIGN KEY (AircraftId) REFERENCES Aircraft(Id),
	FOREIGN KEY (PilotId) REFERENCES Pilots(Id),
)

CREATE TABLE Airports
(
	Id INT PRIMARY KEY IDENTITY,
	AirportName NVARCHAR(70) NOT NULL UNIQUE,
	Country NVARCHAR(100) NOT NULL UNIQUE
)

CREATE TABLE FlightDestinations
(
	Id INT PRIMARY KEY IDENTITY,
	AirportId INT NOT NULL,
	FOREIGN KEY (AirportId) REFERENCES Airports(Id),
	[Start] DATETIME  NOT NULL,
	AircraftId INT  NOT NULL,
	FOREIGN KEY (AircraftId) REFERENCES Aircraft(Id),
	PassengerId INT  NOT NULL,
	FOREIGN KEY (PassengerId) REFERENCES Passengers(Id),
	TicketPrice DECIMAL(18,2) NOT NULL DEFAULT 15
)
